"""library items

Revision ID: ac8eea463cbe
Revises: bafc6269b2ca
Create Date: 2026-10-08 20:08:32.599612
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ac8eea463cbe'
down_revision: str | None = 'bafc6269b2ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('relpath', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_items_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_items_status'))
        batch_op.drop_index(batch_op.f('ix_library_items_name'))
        batch_op.drop_index(batch_op.f('ix_library_items_kind'))
        batch_op.drop_index(batch_op.f('ix_library_items_job_id'))

    op.drop_table('library_items')
    # ### end Alembic commands ###
